name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: project-827c5156-ecae-479b-bb9
  REGION: us-central1
  REPOSITORY: hello-repo
  SERVICE: hello-cloud-run

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:

      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2

      - run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/hello:${{ github.sha }} .

      - run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/hello:${{ github.sha }}

      - run: |
          gcloud run deploy $SERVICE \
          --image=$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/hello:${{ github.sha }} \
          --region=$REGION \
          --platform=managed \
          --allow-unauthenticated
